version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: shrine
    main: .
    binary: shrine
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: shrine
    name_template: "shrine_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: CarlosHPlata
    name: shrine
  draft: false
  prerelease: auto
  name_template: "shrine {{.Tag}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
