// Package docsgen produces Markdown reference pages for the Shrine CLI's
// Cobra command tree, suitable for direct ingestion by the Hugo docs site.
//
// This package is part of a separate Go module (docs/tools/docsgen) so that
// its dependencies — notably github.com/spf13/cobra/doc — never reach the
// main shrine binary's import graph. See the project memory note
// "Auxiliary tooling lives in a separate Go module" for the rationale.
package docsgen

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const banner = "<!-- AUTO-GENERATED by `make docs-gen-cli` — DO NOT EDIT BY HAND. Edits will be overwritten on the next docs build. -->\n\n"

// Options controls Generate.
type Options struct {
	// Clean removes existing *.md files in the output directory (except _index.md)
	// before generating new ones.
	Clean bool
	// IncludeHidden generates pages for Cobra commands marked Hidden: true.
	IncludeHidden bool
}

// Generate walks the command tree of rootCmd and writes one Markdown file per
// non-hidden command into dir.
func Generate(rootCmd *cobra.Command, dir string, opts Options) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}
	if opts.Clean {
		if err := cleanGeneratedFiles(dir); err != nil {
			return fmt.Errorf("cleaning output dir: %w", err)
		}
	}
	return generateCommandTree(rootCmd, dir, opts)
}

// WriteCommand renders a single command (front-matter, banner, Cobra body)
// to w. Exposed for in-memory unit tests that must not touch the filesystem.
func WriteCommand(cmd *cobra.Command, w io.Writer) error {
	if _, err := io.WriteString(w, frontMatterFor(cmd)); err != nil {
		return err
	}
	if _, err := io.WriteString(w, banner); err != nil {
		return err
	}
	prevAutoGenTag := cmd.DisableAutoGenTag
	cmd.DisableAutoGenTag = true
	defer func() { cmd.DisableAutoGenTag = prevAutoGenTag }()
	return doc.GenMarkdownCustom(cmd, w, linkHandler)
}

// ShouldSkipCommand decides whether to skip a command during traversal.
// Hidden commands and Cobra's auto-generated `help` are always skipped
// unless includeHidden is true.
func ShouldSkipCommand(cmd *cobra.Command, includeHidden bool) bool {
	if cmd.Name() == "help" {
		return true
	}
	if includeHidden {
		return false
	}
	return cmd.Hidden
}

func generateCommandTree(cmd *cobra.Command, dir string, opts Options) error {
	if ShouldSkipCommand(cmd, opts.IncludeHidden) {
		return nil
	}
	if cmd.HasParent() {
		if err := writeMarkdownForCommand(cmd, dir); err != nil {
			return err
		}
	}
	for _, child := range cmd.Commands() {
		if err := generateCommandTree(child, dir, opts); err != nil {
			return err
		}
	}
	return nil
}

func writeMarkdownForCommand(cmd *cobra.Command, dir string) error {
	name := commandFileBase(cmd)
	path := filepath.Join(dir, name+".md")
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	return WriteCommand(cmd, f)
}

func commandFileBase(cmd *cobra.Command) string {
	full := strings.ReplaceAll(cmd.CommandPath(), " ", "_")
	return strings.TrimPrefix(full, "shrine_")
}

func frontMatterFor(cmd *cobra.Command) string {
	return fmt.Sprintf(`---
title: "%s"
description: "%s"
weight: 10
---

`, cmd.Name(), escapeYAMLDoubleQuoted(cmd.Short))
}

func escapeYAMLDoubleQuoted(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// linkHandler rewrites underscore-style links emitted by cobra/doc into
// hyphenated Hugo-friendly slugs (apply_teams.md → apply-teams).
func linkHandler(name string) string {
	base := strings.TrimSuffix(name, ".md")
	return strings.ReplaceAll(base, "_", "-") + "/"
}

func cleanGeneratedFiles(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		base := e.Name()
		if filepath.Ext(base) != ".md" {
			continue
		}
		if base == "_index.md" {
			continue
		}
		if err := os.Remove(filepath.Join(dir, base)); err != nil {
			return err
		}
	}
	return nil
}
